# Site settings
title: Jens Norgaard
email: your-email@domain.com
url: http://me5.jnorgaard.com
description: "Lorem ipsizzle dolor sizzle black, pimpin' adipiscing elit. Nullam sapizzle sheezy, ma nizzle volutpizzle, ma nizzle quizzle, i'm in the shizzle vel, fizzle. Pellentesque for sure tortizzle. Sed erizzle. Fo shizzle pimpin' dolizzle dapibus turpis tempizzle yo mamma. Mauris pellentesque pimpin' izzle turpizzle. Vestibulum izzle tortizzle. Pellentesque things rhoncizzle gizzle. In mah nizzle fo shizzle platea dictumst. Donec dapibus"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Curabitizzle tellizzle gizzle

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
